name: GitHub Pages

on:
  push:
    branches:
      - main  # 确保这里是你本地的主分支名称，现在通常是 main，旧项目可能是 master

jobs:
  build-deploy:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # 获取子模块（Blowfish通常作为子模块安装）
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest" # 使用最新版 Hugo

      - name: Build
        run: hugo --minify # 构建并压缩网站

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }} # 确保只在主分支推送时部署
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 这里的 Token 也是自动生成的，不用手动改
          publish_branch: gh-pages  # 构建好的网页会推送到这个分支
          publish_dir: ./public     # 发布的目录